version: "3.8"

services: 
    backend:
        image: devops/backend
        build:
            context: ./backend
        ports:
            - "8081:8081"
        volumes:
            - ./data-from-container.txt:/app/data.txt
        networks:
            - lab-network
        restart: unless-stopped

    frontend:
        depends_on:
            backend:
                condition: service_started
        image: devops/frontend
        build:
            context: ./frontend
        ports:
            - "8080:8080"
        environment:
            - API_URL=http://backend:8081/api/v2
        networks:
            - lab-network
        restart: unless-stopped


networks:
    lab-network:
        driver: bridge
      
